export const ADD_PATIENT_SUCCESS = 'ADD_PATIENT_SUCCESS'
export const ADD_PATIENT_FAIL = 'ADD_PATIENT_FAIL'
export const FETCH_PATIENT_SUCCESS = 'FETCH_PATIENT_SUCCESS'
export const FETCH_PATIENT_FAIL = 'FETCH_PATIENT_SUCCESS'
export const FETCH_PATIENTID_SUCCESS = 'FETCH_PATIENTID_SUCCESS'
export const FETCH_PATIENTID_FAIL = 'FETCH_PATIENTID_FAIL'

